Cypress.Commands.add('fillFormAndSubmit',() =>{
    cy.get('#nome').as('name').type('Gabriel')
    cy.get('#sobrenome').as('LastName').type('Logan')
    cy.get('#email').as('email').type('emailtesting@gmail.com')
    cy.get('input[type="radio"][value="fullstack"]').as('fullstackRadio').check()
    cy.get('#senioridade').as('seniority').select('Sênior')
    cy.get('input[type="checkbox"][value="HTML"]').as('HTMLcheckBox').check()
    cy.get('input[type="checkbox"][value="CSS"]').as('CSScheckBox').check()
    cy.get('input[type="checkbox"][value="Javascript"]').as('JScheckBox').check()
    cy.get('.botao').click()
})

Cypress.Commands.add('assertsFormInitialState', () => {
    cy.get('@name').should('be.empty')
    cy.get('@LastName').should('be.empty')
    cy.get('@email').should('be.empty')
    cy.get('@fullstackRadio').should('not.be.checked')
    cy.get('input[type="radio"][value="frontend"]').should('be.checked')
    cy.get('@seniority').find('option').contains('Selecione').should('be.selected')
    cy.get('@HTMLcheckBox').should('not.be.checked')
    cy.get('@CSScheckBox').should('not.be.checked')
    cy.get('@JScheckBox').should('not.be.checked')
    cy.get('input[type="checkbox"][value="PHP"]').should('not.be.checked')
    cy.get('input[type="checkbox"][value="C#"]').should('not.be.checked')
    cy.get('input[type="checkbox"][value="Python"]').should('not.be.checked')
    cy.get('input[type="checkbox"][value="Java"]').should('not.be.checked')
})